// API 에러 코드 단일 사전입니다.
export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  EXTERNAL_AI_ERROR: "EXTERNAL_AI_ERROR",
  INSUFFICIENT_AI_TOKENS: "INSUFFICIENT_AI_TOKENS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
