// 알림 종류 식별자를 정의합니다.
export const NOTIFICATION_TYPES = {
  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  DEADLINE_SOON: "DEADLINE_SOON",
  SUBMISSION_CREATED: "SUBMISSION_CREATED",
  LATE_SUBMISSION_CREATED: "LATE_SUBMISSION_CREATED",
  COMMENT_ON_MY_SUBMISSION: "COMMENT_ON_MY_SUBMISSION",
  REVIEW_ON_MY_SUBMISSION: "REVIEW_ON_MY_SUBMISSION",
  REPLY_ON_MY_REVIEW: "REPLY_ON_MY_REVIEW",
  REPLY_ON_REVIEW_I_WROTE: "REPLY_ON_REVIEW_I_WROTE",
  REACTION_ON_MY_REVIEW_THREAD: "REACTION_ON_MY_REVIEW_THREAD",
  REPLY_ON_MY_COMMENT: "REPLY_ON_MY_COMMENT",
  AI_ANALYSIS_DONE: "AI_ANALYSIS_DONE",
  AI_ANALYSIS_FAILED: "AI_ANALYSIS_FAILED",
  PROBLEM_ANALYSIS_DONE: "PROBLEM_ANALYSIS_DONE",
  PROBLEM_ANALYSIS_FAILED: "PROBLEM_ANALYSIS_FAILED",
  FEEDBACK_OPENED: "FEEDBACK_OPENED",
  ANNOUNCEMENT_CREATED: "ANNOUNCEMENT_CREATED",
  ANNOUNCEMENT_UPDATED: "ANNOUNCEMENT_UPDATED",
  COMMUNITY_COMMENT_CREATED: "COMMUNITY_COMMENT_CREATED",
  MENTIONED: "MENTIONED",
  JOIN_REQUEST_CREATED: "JOIN_REQUEST_CREATED",
  JOIN_REQUEST_APPROVED: "JOIN_REQUEST_APPROVED",
  JOIN_REQUEST_REJECTED: "JOIN_REQUEST_REJECTED",
} as const;

export type NotificationType = keyof typeof NOTIFICATION_TYPES;
