// 과제 알고리즘 키워드를 현재 언어에 맞는 라벨로 변환합니다.
export const ASSIGNMENT_ALGORITHM_KEYWORDS = [
  "구현",
  "자료구조",
  "완전탐색",
  "브루트포스",
  "BFS",
  "DFS",
  "그리디",
  "이진탐색",
  "매개변수탐색",
  "DP",
  "트리DP",
  "비트DP",
  "메모이제이션",
  "최단경로",
  "그래프",
  "백트래킹",
  "비트마스킹",
  "다익스트라",
  "정렬",
  "해시",
  "문자열",
  "파싱",
  "트리",
  "큐",
  "스택",
  "덱",
  "우선순위큐",
  "힙",
  "시뮬레이션",
  "수학",
  "기하",
  "정수론",
  "누적합",
  "차분배열",
  "투포인터",
  "슬라이딩윈도우",
  "유니온파인드",
  "분할정복",
  "재귀",
  "플로이드워셜",
  "벨만포드",
  "위상정렬",
  "강한연결요소",
  "최소신장트리",
  "세그먼트트리",
  "펜윅트리",
  "희소배열",
  "트라이",
  "최대유량",
  "이분매칭",
  "네트워크플로우",
  "기타",
] as const;

const EN_LABELS: Record<string, string> = {
  구현: "Implementation",
  자료구조: "Data Structure",
  완전탐색: "Exhaustive Search",
  브루트포스: "Brute Force",
  BFS: "BFS",
  DFS: "DFS",
  그리디: "Greedy",
  이진탐색: "Binary Search",
  매개변수탐색: "Parametric Search",
  DP: "DP",
  트리DP: "Tree DP",
  비트DP: "Bitmask DP",
  메모이제이션: "Memoization",
  최단경로: "Shortest Path",
  그래프: "Graph",
  백트래킹: "Backtracking",
  비트마스킹: "Bitmasking",
  다익스트라: "Dijkstra",
  정렬: "Sorting",
  해시: "Hash",
  문자열: "String",
  파싱: "Parsing",
  트리: "Tree",
  큐: "Queue",
  스택: "Stack",
  덱: "Deque",
  우선순위큐: "Priority Queue",
  힙: "Heap",
  시뮬레이션: "Simulation",
  수학: "Math",
  기하: "Geometry",
  정수론: "Number Theory",
  누적합: "Prefix Sum",
  차분배열: "Difference Array",
  투포인터: "Two Pointers",
  슬라이딩윈도우: "Sliding Window",
  유니온파인드: "Union-Find",
  분할정복: "Divide and Conquer",
  재귀: "Recursion",
  플로이드워셜: "Floyd-Warshall",
  벨만포드: "Bellman-Ford",
  위상정렬: "Topological Sort",
  강한연결요소: "Strongly Connected Components",
  최소신장트리: "Minimum Spanning Tree",
  세그먼트트리: "Segment Tree",
  펜윅트리: "Fenwick Tree",
  희소배열: "Sparse Table",
  트라이: "Trie",
  최대유량: "Max Flow",
  이분매칭: "Bipartite Matching",
  네트워크플로우: "Network Flow",
  기타: "Others",
};

const PLATFORM_LABELS: Record<string, { ko: string; en: string }> = {
  BOJ: { ko: "백준", en: "BOJ" },
  Programmers: { ko: "프로그래머스", en: "Programmers" },
  LeetCode: { ko: "리트코드", en: "LeetCode" },
};

export function formatAssignmentAlgorithmLabel(locale: "ko" | "en", keyword: string): string {
  if (locale === "ko") return keyword;
  return EN_LABELS[keyword] ?? keyword;
}

export function formatProblemPlatformLabel(locale: "ko" | "en", platform: string): string {
  const label = PLATFORM_LABELS[platform];
  if (label === undefined) return platform;
  return locale === "ko" ? label.ko : label.en;
}
